name: Fetch Chrome User Agent

on:
    schedule:
        - cron: "0 * * * *" # every hour; adjust as needed
    workflow_dispatch: # manual trigger
    
permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install puppeteer@latest --save

            - name: Run Puppeteer to fetch UA
              run: npm start

            - name: Commit updated package files and ua.json
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add ua.json package.json package-lock.json
                git commit -m "Update user agent and dependencies"
                git push
              env:
                  # To push to the repo, you need a GitHub token, automatically provided as GITHUB_TOKEN
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
